-- TABLA USUARIOS

CREATE TABLE USERS(
FIRSTNAME VARCHAR2(50),
SURNAME VARCHAR2(100),
DNI VARCHAR2(15) NOT NULL UNIQUE,
EMAIL VARCHAR2(50),
USERNAME VARCHAR2(50) NOT NULL UNIQUE,
PASS VARCHAR2(20) NOT NULL,
ROL VARCHAR(5) DEFAULT 'USER' NOT NULL,
ID_USER VARCHAR2(5) CONSTRAINT PK_IDUSER PRIMARY KEY
);


-- TABLA PROVEEDORES 

CREATE TABLE PROVIDERS(
PROVIDER VARCHAR2(50),
CIF VARCHAR2(15) NOT NULL UNIQUE,
ADDRESS VARCHAR2(100),
COUNTRY VARCHAR2(20),
ID_PROVIDER VARCHAR2(5) CONSTRAINT PK_IDSUPPLIER PRIMARY KEY
);


-- TABLA CATEGORIAS 

CREATE TABLE CATEGORY(
TIPO VARCHAR2(20),
ID_CATEGORY VARCHAR2(5) CONSTRAINT PK_IDCATEGORY PRIMARY KEY
);

-- TABLA PRODUCTOS

CREATE TABLE PRODUCTS(
PRONAME VARCHAR2(50),
COUNTRY VARCHAR2(10),
INTENSITY VARCHAR2(2),
PRICE NUMBER(5),
IMG VARCHAR2(100),
ID_CATEGORY VARCHAR2(5),
ID_PRODUCT VARCHAR2(5) CONSTRAINT PK_IDPRODUCT PRIMARY KEY,
CONSTRAINT FK_IDCATEGORY FOREIGN KEY (ID_CATEGORY) REFERENCES CATEGORY(ID_CATEGORY) ON DELETE SET NULL
);

-- TABLA PROVEEDORES

CREATE TABLE SUPLLIES(
ID_PROVIDER VARCHAR2(5),
ID_PRODUCT VARCHAR2(5),
CONSTRAINT FK_IDPROVIDER FOREIGN KEY (ID_PROVIDER) REFERENCES PROVIDERS(ID_PROVIDER) ON DELETE SET NULL,
CONSTRAINT FK_IDPRODUCT FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCTS(ID_PRODUCT) ON DELETE SET NULL
);


-- TABLA ORDENES

CREATE TABLE ORDERS(
FECHA DATE,
ORDER_NUMBER VARCHAR2(100), 
ID_ORDER VARCHAR2(5) CONSTRAINT PK_IDORDER PRIMARY KEY
);

-- TABLA DETALLES 

CREATE TABLE DETAILS(
QUANTITY VARCHAR2(5),
ID_USER VARCHAR2(5),
ID_PRODUCT VARCHAR2(5),
ID_ORDER VARCHAR(5),
ID_DETAIL VARCHAR2(5) CONSTRAINT PK_IDDETAIL PRIMARY KEY,
CONSTRAINT FK_IDUSER FOREIGN KEY (ID_USER) REFERENCES USERS(ID_USER) ON DELETE SET NULL,
CONSTRAINT FK_IDPRODUCT2 FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCTS(ID_PRODUCT) ON DELETE SET NULL,
CONSTRAINT FK_IDORDER FOREIGN KEY (ID_ORDER) REFERENCES ORDERS(ID_ORDER) ON DELETE CASCADE
);




